"""
ortho_tools/publisher.py — Ortho pipeline output publisher.

Writes ortho_metadata.json to the session maps directory after TileCutter
completes.  meshview.html reads this file to configure the Leaflet slippy-map
tab: tile URL template, geographic bounds, zoom range, and GPS waypoints.

Schema written to ortho_metadata.json
--------------------------------------
{
  "session_id":   str,          # e.g. "scan_20260424_221106"
  "mode":         str,          # "fast" | "full"
  "timestamp":    str,          # ISO 8601 UTC
  "tile_url":     str,          # relative URL template for meshview.html
                                #   e.g. "rosbags/scan_.../ortho/tiles/{z}/{x}/{y}.png"
  "bounds": {                   # WGS-84 bounding box (null if no GPS)
    "lat_min": float,
    "lat_max": float,
    "lon_min": float,
    "lon_max": float,
  },
  "zoom_min":     int,          # minimum tile zoom level
  "zoom_max":     int,          # maximum tile zoom level
  "frame_count":  int,          # frames that produced this mosaic
  "gps_count":    int,          # frames with valid GPS coordinates
  "collage_fallback": bool,     # True if Stitcher failed and collage was used
  "processing_s": float,        # wall-clock seconds for the ortho pipeline
}

The tile_url path is relative to the serve root (rpi_server/serve.py),
following the same convention as latest.json's mesh_ply and cloud_ply fields.
serve.py exposes /rosbags/<session>/ so the tile path resolves correctly
from meshview.html regardless of where the browser loads from.

Dependencies
------------
    json, pathlib, datetime — stdlib only
"""

import json
import logging
import time
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


class OrthoPublisher:
    """
    Writes ortho_metadata.json for meshview.html slippy-map tab.

    Parameters
    ----------
    maps_dir : Path
        Maps output directory (e.g. /mnt/ssd/maps/).  ortho_metadata.json
        is written here so serve.py can serve it at /maps/ortho_metadata.json.
    """

    def __init__(self, maps_dir: Path) -> None:
        self.maps_dir = Path(maps_dir)

    # ── Public API ────────────────────────────────────────────────────────────

    def publish(
        self,
        session_id:       str,
        session_dir:      Path,
        tile_dir:         Path,
        zoom_min:         int,
        zoom_max:         int,
        mode:             str,
        geo:              Optional[dict],
        frame_count:      int,
        collage_fallback: bool   = False,
        processing_s:     float  = 0.0,
    ) -> Path:
        """
        Write ortho_metadata.json and return its path.

        Parameters
        ----------
        session_id       : str  — e.g. "scan_20260424_221106"
        session_dir      : Path — session bag/output directory
        tile_dir         : Path — directory containing tiles/{z}/{x}/{y}.png
        zoom_min         : int  — minimum zoom generated by TileCutter
        zoom_max         : int  — maximum zoom generated by TileCutter
        mode             : str  — "fast" or "full"
        geo              : dict or None — GPS bounds from MosaicBuilder
        frame_count      : int  — number of frames that produced the mosaic
        collage_fallback : bool — True if cv2.Stitcher failed
        processing_s     : float — total ortho pipeline wall-clock seconds

        Returns
        -------
        Path to the written ortho_metadata.json.
        """
        self.maps_dir.mkdir(parents=True, exist_ok=True)

        # Build tile URL relative to serve root.
        # tile_dir is typically:
        #   /mnt/ssd/rosbags/scan_YYYYMMDD_HHMMSS/ortho/tiles
        # serve.py exposes /rosbags/<session>/ so the relative path is:
        #   rosbags/<session>/ortho/tiles/{z}/{x}/{y}.png
        try:
            # Compute relative path from serve root's rosbags parent
            rosbags_root = session_dir.parent
            rel          = tile_dir.relative_to(rosbags_root)
            tile_url = f"rosbags/{rel.as_posix()}/{{z}}/{{x}}/{{y}}.png"
        except ValueError:
            # tile_dir is not under the expected rosbags root (dev/Windows)
            tile_url = f"rosbags/{session_id}/ortho/tiles/{{z}}/{{x}}/{{y}}.png"

        # Normalise geo bounds
        bounds = None
        gps_count = 0
        if geo is not None:
            bounds = {
                "lat_min": round(geo["lat_min"], 8),
                "lat_max": round(geo["lat_max"], 8),
                "lon_min": round(geo["lon_min"], 8),
                "lon_max": round(geo["lon_max"], 8),
            }
            gps_count = geo.get("gps_count", 0)

        payload = {
            "session_id":       session_id,
            "mode":             mode,
            "timestamp":        datetime.now(tz=timezone.utc).strftime(
                                    "%Y-%m-%dT%H:%M:%SZ"
                                ),
            "tile_url":         tile_url,
            "bounds":           bounds,
            "zoom_min":         zoom_min,
            "zoom_max":         zoom_max,
            "frame_count":      frame_count,
            "gps_count":        gps_count,
            "collage_fallback": collage_fallback,
            "processing_s":     round(processing_s, 1),
        }

        out_path = self.maps_dir / "ortho_metadata.json"
        out_path.write_text(json.dumps(payload, indent=2))
        logger.info(f"[OrthoPublisher] Written: {out_path}")
        print(f"  [OrthoPublisher] ortho_metadata.json → {out_path}")

        if bounds:
            print(
                f"  [OrthoPublisher] Bounds: "
                f"lat [{bounds['lat_min']:.6f}, {bounds['lat_max']:.6f}]  "
                f"lon [{bounds['lon_min']:.6f}, {bounds['lon_max']:.6f}]"
            )
        else:
            print(
                f"  [OrthoPublisher] No GPS bounds — slippy map will not "
                f"auto-center.  Fly with GPS for geographic registration."
            )

        print(f"  [OrthoPublisher] Tile URL: {tile_url}")
        return out_path
